version = 0.1

[default]
[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "twilio-custom-parts-takagi-cancel"
resolve_s3 = true
s3_prefix = "twilio-custom-parts-takagi-cancel"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[dev.deploy.parameters]
stack_name = "twilio-custom-parts-takagi-cancel"
resolve_s3 = true
s3_prefix = "twilio-custom-parts-takagi-cancel"
region = "ap-northeast-1"
confirm_changeset = true
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
profile = "dev"

[prod.deploy.parameters]
stack_name = "twilio-custom-parts-takagi-cancel"
resolve_s3 = true
s3_prefix = "twilio-custom-parts-takagi-cancel"
region = "us-east-1"
confirm_changeset = true
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
profile = "prod"
